version: "2"

### Servicios
services:

  ### Nginx
  nginx:    
    container_name: project-nginx
    build:
      context: ./nginx
      args:
        - DOCKER_HTTP_USER=${DOCKER_HTTP_USER}
        - DOCKER_HTTP_PASS=${DOCKER_HTTP_PASS}
    environment:
      - TZ=${TIMEZONE}
    ports:
      - "${HTTP_STD_PORT_IN}:${HTTP_STD_PORT_OUT}"
      - "${HTTPS_STD_PORT_IN}:${HTTPS_STD_PORT_OUT}"
    volumes:
      - /static:/static
    depends_on:
      - django
  
  postgres-django:
    container_name: project-postgres-django
    ports:
        - "${POSTGRES_DJANGO_OUT_PORT}:${POSTGRES_DJANGO_IN_PORT}"
    build: ./postgres
    environment:
        - TZ=${TIMEZONE}
        - POSTGRES_DB=${POSTGRES_DJANGO_DB}
        - POSTGRES_USER=${POSTGRES_DJANGO_USER}
        - POSTGRES_PASSWORD=${POSTGRES_DJANGO_PASSWORD}
    
  django:
    container_name: project-django
    build: ./django
    command: bash -c "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && gunicorn linker.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./sources:/sources
      - /static:/static
    links:
      - postgres-django
    expose:
      - "8000"
