# Generated by Django 2.2.2 on 2019-07-06 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=35)),
                ('Nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('Descripcion', models.CharField(max_length=250)),
                ('Fecha_Creacion', models.DateField(auto_now=True)),
                ('Mostrar_Web', models.CharField(default='0', max_length=1)),
                ('Estado', models.CharField(default='1', max_length=1)),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
            },
        ),
        migrations.CreateModel(
            name='TransaccionTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('Descripcion', models.CharField(max_length=250)),
                ('Fecha_Creacion', models.DateField(auto_now=True)),
                ('Estado', models.CharField(default='1', max_length=1)),
            ],
            options={
                'verbose_name': 'Tipo de Transacción',
                'verbose_name_plural': 'Tipos de Transacción',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Transaccion', models.DateField(auto_now=True)),
                ('Fecha_Creacion', models.DateField()),
                ('Saldo_Actual', models.IntegerField(default=0)),
                ('Estado', models.BooleanField(default=True)),
                ('Articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Inventario.Articulo')),
                ('TransaccionTipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Inventario.TransaccionTipo')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
            },
        ),
    ]
