# Generated by Django 2.2.2 on 2019-07-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Inventario', '0002_auto_20190706_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='Nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
