# Generated by Django 2.2.2 on 2019-07-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Inventario', '0003_auto_20190707_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='Estado',
            field=models.CharField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='Mostrar_Web',
            field=models.CharField(choices=[(0, 'No'), (1, 'Si')], default=0, max_length=1),
        ),
    ]
