# Generated by Django 2.2.2 on 2019-07-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Inventario', '0004_auto_20190707_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='Estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='Mostrar_Web',
            field=models.BooleanField(default=False),
        ),
    ]
